#!/usr/bin/env bash
# ⚠️  ALREADY RUN — 2026-09-04. Re-running will create 50 duplicate issues,
# since issue creation (unlike label creation) is not idempotent.
# Kept for reference / in case issues need to be recreated in a fresh repo.
set -euo pipefail

# =====================================================================
# Creates GitHub labels + issues for every FR/NFR in IMPLEMENTATION_BACKLOG.md
#
# Usage:
#   Run from inside the cloned subscribe-master repo directory, with the
#   GitHub CLI (gh) already authenticated (`gh auth status` to check).
#
#     chmod +x create_github_issues.sh
#     ./create_github_issues.sh
#
# If running from outside the repo directory, add --repo cptrobie/subscribe-master
# to every `gh label create` / `gh issue create` call below.
# =====================================================================

echo "Creating labels..."

gh label create "wave-0" --color "0e8a16" --description "Wave 0 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-1" --color "1d76db" --description "Wave 1 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-2" --color "5319e7" --description "Wave 2 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-3" --color "b60205" --description "Wave 3 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-4" --color "d93f0b" --description "Wave 4 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-5" --color "fbca04" --description "Wave 5 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-6" --color "0052cc" --description "Wave 6 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-7" --color "006b75" --description "Wave 7 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-8" --color "c2e0c6" --description "Wave 8 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-9" --color "bfd4f2" --description "Wave 9 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-10" --color "d4c5f9" --description "Wave 10 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "wave-11" --color "f9d0c4" --description "Wave 11 in IMPLEMENTATION_BACKLOG.md" --force
gh label create "size-S" --color "c5f015" --description "Small: half a day or less" --force
gh label create "size-M" --color "fbca04" --description "Medium: 1-2 days" --force
gh label create "size-L" --color "e11d21" --description "Large: 3+ days / spans multiple sessions" --force
gh label create "standing-convention" --color "cccccc" --description "Enforced continuously, not a one-time closeable task - see IMPLEMENTATION_BACKLOG.md" --force

echo "Labels created. Creating issues..."

gh issue create --title "[NFR-13] Set up Flyway and wire migrations into the build" --label "wave-0" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-13`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-12] Docker Compose single-command startup" --label "wave-0" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-12`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-08] Environment-based configuration (dev/prod profiles, no hardcoded secrets)" --label "wave-0" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-08`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-20] Vault integration for secrets management (all environments, including local dev)" --label "wave-0" --label "size-L" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-20`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-19] CI/CD pipeline for build, test, and deploy" --label "wave-0" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-19`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-09] Set up API documentation (Swagger/OpenAPI)" --label "wave-0" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-09`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-01] Establish layered architecture (Controller to Service to Repository to Entity)" --label "wave-0" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-01`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."
gh issue create --title "[NFR-14] Establish constructor-injection-only convention" --label "wave-0" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-14`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."
gh issue create --title "[NFR-15] Establish LAZY-fetching convention" --label "wave-0" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-15`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."
gh issue create --title "[NFR-16] Establish JPQL/Specification API convention (no native SQL)" --label "wave-0" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-16`).\n\nPart of Wave 0 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."
gh issue create --title "[FR-01] User registration endpoint (/auth/register)" --label "wave-1" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-01`).\n\nPart of Wave 1 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-02] User login endpoint (/auth/login)" --label "wave-1" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-02`).\n\nPart of Wave 1 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-03] Password hashing (BCrypt)" --label "wave-1" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-03`).\n\nPart of Wave 1 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-04] Per-user data isolation / authorization enforcement" --label "wave-1" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-04`).\n\nPart of Wave 1 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-02] Global exception handling" --label "wave-1" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-02`).\n\nPart of Wave 1 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-06] Role-based access control (staff roles/permissions)" --label "wave-2" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-06`).\n\nPart of Wave 2 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-05] Refresh token mechanism" --label "wave-2" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-05`).\n\nPart of Wave 2 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-07] Subscription CRUD (name, price, currency, start date, frequency)" --label "wave-3" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-07`).\n\nPart of Wave 3 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-08] Automatic next-payment-date calculation" --label "wave-3" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-08`).\n\nPart of Wave 3 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-09] Subscription status enum (ACTIVE/PAUSED/CANCELLED)" --label "wave-3" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-09`).\n\nPart of Wave 3 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-04] Optimistic locking on customer_subscriptions and payment_history" --label "wave-3" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-04`).\n\nPart of Wave 3 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-10] Pagination and filtering (Specification API, status/currency/price range)" --label "wave-4" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-10`).\n\nPart of Wave 4 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-11] Soft delete for subscriptions" --label "wave-4" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-11`).\n\nPart of Wave 4 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-27] Category grouping" --label "wave-4" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-27`).\n\nPart of Wave 4 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-13] Base currency tracking per customer" --label "wave-5" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-13`).\n\nPart of Wave 5 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-14] Real-time exchange rate integration (cbu.uz)" --label "wave-5" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-14`).\n\nPart of Wave 5 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-15] Exchange rate caching" --label "wave-5" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-15`).\n\nPart of Wave 5 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-05] Exchange rate caching (performance criterion, same implementation as FR-15)" --label "wave-5" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-05`).\n\nPart of Wave 5 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-17] Rate date transparency" --label "wave-5" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-17`).\n\nPart of Wave 5 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-16] Resilience / fallback (Circuit Breaker) for the rate API" --label "wave-5" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-16`).\n\nPart of Wave 5 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-12] Payment history persistence, including after subscription cancellation" --label "wave-6" --label "size-L" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-12`).\n\nPart of Wave 6 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-03] Transactional integrity on money-related operations" --label "wave-6" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-03`).\n\nPart of Wave 6 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-29] Payment retry / dunning (up to 3 attempts)" --label "wave-7" --label "size-L" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-29`).\n\nPart of Wave 7 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-28] Partial refund support" --label "wave-7" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-28`).\n\nPart of Wave 7 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-18] Daily scheduled payment-due check" --label "wave-8" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-18`).\n\nPart of Wave 8 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-19] Payment-due warning notification (log/email)" --label "wave-8" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-19`).\n\nPart of Wave 8 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-20] Notification strategy abstraction (Strategy pattern)" --label "wave-8" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-20`).\n\nPart of Wave 8 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-21] Scheduler concurrency safety (ShedLock)" --label "wave-8" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-21`).\n\nPart of Wave 8 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-22] Annual cost report export (Excel/CSV)" --label "wave-9" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-22`).\n\nPart of Wave 9 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-23] Report contents (name, monthly price, base equivalent, annual total)" --label "wave-9" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-23`).\n\nPart of Wave 9 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-24] Most expensive subscription statistic" --label "wave-9" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-24`).\n\nPart of Wave 9 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-25] Total monthly spend statistic" --label "wave-9" --label "size-S" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-25`).\n\nPart of Wave 9 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[FR-26] Monthly cost trend (6/12 months, JSON)" --label "wave-9" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `FR-26`).\n\nPart of Wave 9 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-07] Auditing timestamps" --label "wave-10" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-07`).\n\nPart of Wave 10 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."
gh issue create --title "[NFR-17] Audit logging of actor actions" --label "wave-10" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-17`).\n\nPart of Wave 10 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-18] Distributed / request tracing" --label "wave-10" --label "size-M" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-18`).\n\nPart of Wave 10 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-06] Code style compliance (Google Java Style Guide)" --label "wave-11" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-06`).\n\nPart of Wave 11 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."
gh issue create --title "[NFR-10] Clean Code principles" --label "wave-11" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-10`).\n\nPart of Wave 11 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."
gh issue create --title "[NFR-11] Minimum test coverage (30%, JUnit 5 + AssertJ)" --label "wave-11" --label "size-L" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-11`).\n\nPart of Wave 11 in `IMPLEMENTATION_BACKLOG.md`."
gh issue create --title "[NFR-09] API documentation completeness (Swagger, verification pass)" --label "wave-11" --label "size-S" --label "standing-convention" --body "See `subscribe_master_requirements.md` for the full requirement description, schema-coverage status, and design rationale (search for `NFR-09`).\n\nPart of Wave 11 in `IMPLEMENTATION_BACKLOG.md`.\n\n**Standing convention** — this isn't a one-time feature; it's enforced continuously across future PRs (e.g. via code review checklist or a linter rule), not something that gets "done" once and forgotten. See `IMPLEMENTATION_BACKLOG.md` for the full explanation of this distinction."

echo "Done. Created 50 issues."
