package com.acuity.subscribemaster.error;

/** Stable, machine-readable error identifiers returned in {@link ApiError#code()}. */
public enum ErrorCode {
  VALIDATION_FAILED,
  MALFORMED_REQUEST,
  MISSING_HEADER,
  ACCOUNT_ALREADY_EXISTS,
  NOT_FOUND,
  ACCOUNT_LOCKED,
  INVALID_CREDENTIALS,
  INVALID_SUBSCRIPTION_IDENTITY,
  INVALID_STATE_TRANSITION,
  IDEMPOTENCY_KEY_MISMATCH,
  IDEMPOTENCY_KEY_PROCESSING,
  INTERNAL_ERROR
}
