package com.acuity.subscribemaster.auditlog;

public enum AuditAction {
  REGISTERED,
  ACCOUNT_LOCKED,
  REGISTRATION_REJECTED,
  SUBSCRIPTION_CREATED,
  SUBSCRIPTION_CANCELLED,
  SUBSCRIPTION_PAUSED,
  SUBSCRIPTION_RESUMED,
  SUBSCRIPTION_UPDATED
}
